name: Workflow to Build and Push Multi-platform
# Reference: https://docs.docker.com/build/ci/github-actions/multi-platform/

# Run workflow on every push to main branch
# Reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!README.md'
      - '!LICENSE'

  schedule:
    - cron: '0 0 * * *' # Example: Runs every day at midnight UTC
    # - cron: '0 13 * * *' # Evety day at 13:00 UTC. Every day at 09:00 GMT-4 (Campo Grande/MS) ===> 09 + 4 = 13 UTC

  workflow_dispatch:  # Example: Runs workflow manually
  
# Your workflows jobs
# Reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do repositório de código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: jarbelix/generate-fake-ldif:latest
          platforms: linux/amd64, linux/arm64
          push: true
